# Configuración para escalamiento global - Fase 4
infrastructure:
  auto_scaling:
    enabled: true
    min_nodes: 100
    max_nodes: 1000
    metrics:
      - cpu_utilization: 70%
      - memory_utilization: 75%
      - network_throughput: 1Gbps
  
  regions:
    - north_america:
        nodes: 200
        storage: 500TB
        types: [inference, validation, storage]
    - europe:
        nodes: 150
        storage: 400TB
        types: [inference, validation, storage]
    - asia_pacific:
        nodes: 150
        storage: 400TB
        types: [inference, validation, storage]
    - south_america:
        nodes: 50
        storage: 100TB
        types: [inference, storage]
    - africa:
        nodes: 50
        storage: 100TB
        types: [inference, storage]

performance_optimization:
  query_optimization:
    enabled: true
    cache_size: 100GB
    index_strategy: composite
  memory_management:
    garbage_collection: automatic
    compression: zstd
    tiered_storage: [ssd, hdd, cold_storage]
  network_optimization:
    cdn_integration: true
    peer_optimization: true
    latency_optimization: true

developer_ecosystem:
  api_rate_limits:
    free_tier: 1000 requests/day
    paid_tier: 100000 requests/day
    enterprise: unlimited
  sdk_support:
    languages: [python, javascript, rust, go, java, csharp]
    documentation: comprehensive
    examples: extensive
  community_grants:
    budget: 1000000 NEXUS
    focus_areas: [scaling_solutions, security, new_features]