apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-core
  namespace: nexus
  labels:
    app: nexus-core
    component: reasoning
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nexus-core
      component: reasoning
  template:
    metadata:
      labels:
        app: nexus-core
        component: reasoning
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: nexus-service-account
      containers:
      - name: nexus-reasoning
        image: nexusai/nexus-core:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http-metrics
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: 1
          limits:
            memory: "32Gi"
            cpu: "8"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10